# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-21 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='topic',
            name='top_name',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='name',
            field=models.CharField(max_length=264),
        ),
    ]
