# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-21 03:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20180121_0258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='phone_number',
        ),
    ]
