# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-21 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_remove_userinfo_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='company',
            field=models.CharField(default='test', max_length=50),
        ),
    ]
